# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll", "3.9.0"
gem "liquid-c"
gem "github-pages-health-check", "1.16.1"
gem "github-pages", "207"
gem "html-pipeline", "2.13.0"
gem "jekyll-avatar", "0.7.0"
gem "jekyll-coffeescript", "1.1.1"
gem "jekyll-commonmark-ghpages", "0.1.6"
gem "jekyll-default-layout", "0.1.4"
gem "jekyll-feed", "0.13.0"
gem "jekyll-include-cache"
gem "jekyll-gist", "1.5.0"
gem "jekyll-github-metadata", "2.13.0"
gem "jekyll-mentions", "1.5.1"
gem "jekyll-optional-front-matter", "0.3.2"
gem "jekyll-paginate", "1.1.0"
gem "jekyll-readme-index", "0.3.0"
gem "jekyll-redirect-from", "0.15.0"
gem "jekyll-relative-links", "0.6.1"
gem "jekyll-remote-theme", "0.4.1"
gem "jekyll-sass-converter", "1.5.2"
gem "jekyll-seo-tag", "2.6.1"
gem "jekyll-sitemap", "1.4.0"
gem "jekyll-swiss", "1.0.0"
gem "jekyll-theme-architect", "0.1.1"
gem "jekyll-theme-cayman", "0.1.1"
gem "jekyll-theme-dinky", "0.1.1"
gem "jekyll-theme-hacker", "0.1.1"
gem "jekyll-theme-leap-day", "0.1.1"
gem "jekyll-theme-merlot", "0.1.1"
gem "jekyll-theme-midnight", "0.1.1"
gem "jekyll-theme-minimal", "0.1.1"
gem "jekyll-theme-modernist", "0.1.1"
gem "jekyll-theme-primer", "0.5.4"
gem "jekyll-theme-slate", "0.1.1"
gem "jekyll-theme-tactile", "0.1.1"
gem "jekyll-theme-time-machine", "0.1.1"
gem "jekyll-titles-from-headings", "0.5.3"
gem "jemoji", "0.11.1"
# gem "kramdown-parser-gfm", "1.1.0"
# gem "kramdown", "2.3.0"
gem "jekyll-commonmark"
gem "liquid", "4.0.3"
gem "minima", "2.5.1"
gem "nokogiri", "1.11.4"
gem "rouge", "3.19.0"
gem "safe_yaml", "1.0.5"
gem "sass", "3.7.4"
